version: "3"

tasks:
  fmt:
    desc: Format Go files
    cmds:
      - gofmt -w $(find . -name '*.go' -type f)

  fmt:check:
    desc: Fail when gofmt would change files
    cmds:
      - test -z "$(gofmt -l $(find . -name '*.go' -type f))"

  lint:
    desc: Run static checks
    deps: [fmt:check]
    cmds:
      - go vet ./...

  test:
    desc: Run unit tests
    deps: [fmt:check]
    cmds:
      - go test ./...

  build:
    desc: Ensure package builds
    deps: [fmt:check]
    cmds:
      - go build ./...

  smoke:
    desc: Run deterministic smoke checks
    deps: [fmt:check]
    cmds:
      - go test ./... -run 'Test(ParseArgsBasic|RunCommandSuccess|RunLifecycleOrder|ResolveExitCode)$'

  schema:check:
    desc: Validate JSON contracts against schemas
    deps: [fmt:check]
    cmds:
      - go run ./internal/tools/schemacheck --schema schemas/doctor-report.schema.json --input testdata/contracts/doctor-report.ok.json
      - go run ./internal/tools/schemacheck --schema schemas/scaffold-version-output.schema.json --input testdata/contracts/scaffold-version-output.ok.json

  schema:negative:
    desc: Ensure invalid contract fixtures fail validation
    deps: [fmt:check]
    cmds:
      - sh -c '! go run ./internal/tools/schemacheck --schema schemas/doctor-report.schema.json --input testdata/contracts/doctor-report.bad-missing-findings.json'
      - sh -c '! go run ./internal/tools/schemacheck --schema schemas/doctor-report.schema.json --input testdata/contracts/doctor-report.bad-schema-version.json'
      - sh -c '! go run ./internal/tools/schemacheck --schema schemas/scaffold-version-output.schema.json --input testdata/contracts/scaffold-version-output.bad-missing-date.json'
      - sh -c '! go run ./internal/tools/schemacheck --schema schemas/scaffold-version-output.schema.json --input testdata/contracts/scaffold-version-output.bad-schema-version.json'

  ci:
    desc: Canonical CI contract command
    deps: [lint, test, build, smoke, schema:check, schema:negative]
    cmds:
      - echo "ci checks passed"

  verify:
    desc: Local aggregate verification
    deps: [ci]
    cmds:
      - echo "verify checks passed"

  release:prep:
    desc: Release readiness gate (clean tree + full ci)
    deps: [ci]
    cmds:
      - test -z "$(git status --porcelain)"
      - echo "release prep passed"

  release:build:
    desc: Build multi-arch release artifacts into dist/{{.VERSION}}
    requires:
      vars: [VERSION]
    cmds:
      - test -n "{{.VERSION}}"
      - |
        sh -c 'case "{{.VERSION}}" in
          v*) ;;
          *) echo "VERSION must start with v (example v0.2.2)" >&2; exit 1 ;;
        esac'
      - mkdir -p dist/{{.VERSION}}
      - |
        set -euo pipefail
        for target in "darwin amd64" "darwin arm64" "linux amd64" "linux arm64"; do
          os=$(echo "$target" | awk '{print $1}')
          arch=$(echo "$target" | awk '{print $2}')
          outdir="dist/{{.VERSION}}/agentcli_${os}_${arch}"
          mkdir -p "$outdir"
          GOOS="$os" GOARCH="$arch" CGO_ENABLED=0 go build -o "$outdir/agentcli" ./cmd/agentcli
          cp LICENSE "$outdir/"
          tar -C "dist/{{.VERSION}}" -czf "dist/{{.VERSION}}/agentcli_{{.VERSION}}_${os}_${arch}.tar.gz" "agentcli_${os}_${arch}"
        done
      - sh -c 'cd dist/{{.VERSION}} && shasum -a 256 agentcli_{{.VERSION}}_*.tar.gz > checksums.txt'
      - echo "release artifacts prepared in dist/{{.VERSION}}"

  release:tag:
    desc: Create and push git tag for VERSION
    requires:
      vars: [VERSION]
    cmds:
      - test -n "{{.VERSION}}"
      - git tag -a {{.VERSION}} -m "{{.VERSION}}"
      - git push origin {{.VERSION}}

  release:publish:
    desc: Create GitHub release for VERSION using docs/releases/{{.VERSION}}.md
    requires:
      vars: [VERSION]
    cmds:
      - test -n "{{.VERSION}}"
      - test -f docs/releases/{{.VERSION}}.md
      - test -f dist/{{.VERSION}}/checksums.txt
      - >
        gh release create {{.VERSION}}
        dist/{{.VERSION}}/agentcli_{{.VERSION}}_darwin_amd64.tar.gz
        dist/{{.VERSION}}/agentcli_{{.VERSION}}_darwin_arm64.tar.gz
        dist/{{.VERSION}}/agentcli_{{.VERSION}}_linux_amd64.tar.gz
        dist/{{.VERSION}}/agentcli_{{.VERSION}}_linux_arm64.tar.gz
        dist/{{.VERSION}}/checksums.txt
        --repo gh-xj/agentcli-go
        --title "agentcli-go {{.VERSION}}"
        --notes-file docs/releases/{{.VERSION}}.md

  release:
    desc: End-to-end release flow (prep + build + tag + publish)
    requires:
      vars: [VERSION]
    cmds:
      - task: release:prep
      - task: release:build
        vars:
          VERSION: "{{.VERSION}}"
      - task: release:tag
        vars:
          VERSION: "{{.VERSION}}"
      - task: release:publish
        vars:
          VERSION: "{{.VERSION}}"
